# -*- coding: utf-8 -*-
"""Copia de T48A-P06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMk2C3jjjXQCHf6ChLxAiqwpQFAsW2Jg
"""

#Imports
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df_estudiantes = pd.read_csv('/content/STUDENT_GROUP.csv')
df_asistencia = pd.read_csv('/content/attendance.csv')

# Mostrar primeras filas
print("Muestra de datos de estudiantes:")
print(df_estudiantes.head(3))
print("\nMuestra de datos de asistencia:")
print(df_asistencia.head(3))

# Eliminar registros inválidos
df_asistencia = df_asistencia.dropna(subset=['STUDENT_ID'])
df_asistencia['STUDENT_ID'] = df_asistencia['STUDENT_ID'].astype('int64')

#Unir datos de estudiantes y asistencia

print(df_asistencia.columns)  # Imprimir las columnas de df_asistencia
print(df_estudiantes.columns) # Imprimir las columnas de df_estudiantes

df_combinado = pd.merge(
    df_asistencia,
    df_estudiantes,
    left_on='STUDENT_ID',  # Usar 'left_on' para df_asistencia
    right_on='student_id', # Usar 'right_on' para df_estudiantes
    how='inner'
)

print("Muestra de datos combinados:")
print(df_combinado.head())

df_filtrado = df_combinado[df_combinado['student_id'].notna()]

df_filtrado = df_combinado[df_combinado['group_id'].str.contains('T48A')]

print("Muestra de datos filtrados:")
print(df_filtrado.head())

conteo_estudiantes = df_filtrado.groupby('STUDENT_ID').size()
conteo_estudiantes = conteo_estudiantes.reset_index(name='Asistencias')

conteo_estudiantes['Inasistencias'] = 10- conteo_estudiantes['Asistencias']

try:
    # Primero verificamos si la columna existe y su nombre exacto
    print("Columnas disponibles:", df_filtrado.columns.tolist())

    # Convertir fechas usando el nombre correcto de la columna (DTTM)
    df_filtrado['DTTM'] = pd.to_datetime(df_filtrado['DTTM'], errors='coerce')
    df_filtrado['Dia'] = df_filtrado['DTTM'].dt.day_name()
except KeyError as e:
    print(f"Error: No se encontró la columna. Columnas disponibles: {df_filtrado.columns.tolist()}")
    raise e

print("\nResumen de asistencias por estudiante:")
print(conteo_estudiantes.head())

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(conteo_estudiantes['Asistencias'], bins=10)
plt.title('Distribución de Asistencias')
plt.xlabel('Número de Asistencias')
plt.ylabel('Frecuencia')
plt.show()