# -*- coding: utf-8 -*-
"""DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6CcZBDED40IzUVcXsCaAx_Uns5DiFxL
"""

import pandas as pd
import numpy as np

asistencia = pd.read_csv('/attendance.csv')
studentgroupe = pd.read_csv('/STUDENT_GROUP.csv')

asistencia.columns = ['id', 'student_id', 'date', 'date_time']
studentgroupe.columns = ['id', 'group_id', 'student_id']


studentgroupe['student_id'] = studentgroupe['student_id'].astype(str)
asistencia['student_id'] = asistencia['student_id'].astype(str)

asistencia['date'] = pd.to_datetime(asistencia['date'], errors='coerce')

asistencia = asistencia[asistencia['date'].dt.year == pd.to_datetime('today').year]

filtro = studentgroupe.merge(asistencia, on='student_id', how='inner')
filtro = filtro[filtro['group_id'] == '20251ST48A']

filtro['day'] = filtro['date'].dt.day

filtro2 = filtro.groupby('day').agg(
    asistencia_count=('student_id', 'count'),
    first_assistance_date=('date', 'first'),
    last_assistance_date=('date', 'last'),
    groupid=('group_id', 'first')
)

max_asistencias = filtro2['asistencia_count'].max()

filtro2['faltas'] = max_asistencias - filtro2['asistencia_count']

print(filtro2)

merged_df = pd.merge(df_attendance, df_groups, on='student_id', how= 'inner')

filtered_df = merged_df[merged_df['student_id'].notna()]

filtered_df