# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr1l0_8wxig__lAkBvWCEVyQNKluUC6W
"""

import pandas as pd
df_attendance = pd.read_csv("attendance.csv")
df_groups = pd.read_csv("STUDENT_GROUP.csv")

df_attendance.tail(3)

df_attendance.head(3)

df_groups.dtypes

df_attendance.dtypes

df_attendance.rename(columns={'STUDENT_ID': 'student_id'}, inplace=True)

df_attendance['student_id'] = pd.to_numeric(df_attendance['student_id'], errors='coerce')

df_attendance.dropna(subset=['student_id'], inplace=True)

df_attendance['student_id'] = df_attendance['student_id'].astype(int)

df_attendance.describe()

merged_df = pd.merge(df_attendance, df_groups, on='student_id', how='inner')
filtered_df = merged_df[merged_df['student_id'].notna()]
filtered_df

filtered_df['DT'] = pd.to_datetime(filtered_df['DT'])

# Example value for year to filter by
year_to_filter = 2025  # Replace with the desired year

# Filter the DataFrame by extracting the year
filtered_by_year = filtered_df[filtered_df['DT'].dt.year == year_to_filter]

# Display the filtered DataFrame
filtered_by_year

group_id_to_filter = '20251ST48A'  # Replace with the desired group_id

# Filter the DataFrame
filtered_by_group = filtered_by_year[filtered_by_year['group_id'] == group_id_to_filter]

# Display the filtered DataFrame
filtered_by_group

import pandas as pd

# Assuming filtered_by_group is your DataFrame after filtering by year and group_id

# Convert the 'date' column to datetime if it's not already
filtered_by_group['DT'] = pd.to_datetime(filtered_by_group['DT'])

# Group by date and count the number of attendees
attendance_count = filtered_by_group.groupby('DT').size().reset_index(name='attended_count')

# Calculate the number of missing students
total_students = 23
attendance_count['missing_count'] = total_students - attendance_count['attended_count']

# Display the attendance count DataFrame
attendance_count