# -*- coding: utf-8 -*-
"""P06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpMvI1dNnfq-mtkb68rkYkNMHHAdM3N-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_groups = pd.read_csv('STUDENT_GROUP.csv')
df_attendance = pd.read_csv('attendance.csv')

df_attendance.tail(3)

df_groups.head(3)

df_groups.dtypes
df_attendance.dtypes

df_attendance.columns = ['id', 'student_id', 'date', 'date_time']
df_groups.columns = ['id', 'group_id', 'student_id']

df_groups['student_id'] = df_groups['student_id'].astype(str)
df_attendance['student_id'] = df_attendance['student_id'].astype(str)

df_attendance['date'] = pd.to_datetime(df_attendance['date'], errors='coerce')

df_attendance = df_attendance[df_attendance['date'].dt.year == pd.to_datetime('today').year]

filtro1 = df_groups.merge(df_attendance, on='student_id', how='inner')
filtro1 = filtro1[filtro1['group_id'] == '20251ST48A']
filtro1['day'] = filtro1['date'].dt.day

filtro2 = filtro1.groupby('day').agg(
    asistencia_count=('student_id', 'count'),
    first_assistance_date=('date', 'first'),
    last_assistance_date=('date', 'last'),
    groupid=('group_id', 'first')
)

max_asistencias = filtro2['asistencia_count'].max()

filtro2['Inasistencias'] = max_asistencias - filtro2['asistencia_count']
print(filtro2)

merged_df = pd.merge(df_attendance, df_groups, on='student_id', how= 'inner')
filtered_df = merged_df[merged_df['student_id'].notna()]
filtered_df

