# -*- coding: utf-8 -*-
"""P06_179287.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQ7wMa6kQuKrX4gU_WvmDP7S4_xdl7CW
"""

import pandas as pd
df_alumnos = pd.read_csv("/content/STUDENT_GROUP.csv")
df_attendence = pd.read_csv("/content/attendance.csv")

df_alumnos.head(3)

df_attendence.head(3)

df_alumnos.dtypes

df_attendence.dtypes

df_attendence.rename(columns={'STUDENT_ID' : 'student_id'}, inplace=True)
df_alumnos.rename(columns={'STUDENT_ID' : 'student_id'}, inplace=True)

#convert to numeric
df_attendence['student_id'] = pd.to_numeric(df_attendence['student_id'], errors='coerce')

#"drop rows where id isnt number
df_attendence.dropna(subset=['student_id'], inplace=True)
#Convert id to int64
df_attendence['student_id'] = df_attendence['student_id'].astype('int64')

df_attendence.describe()

merge_df = pd.merge(df_attendence,df_alumnos, on='student_id', how='inner')

filtered_df = merge_df[merge_df['student_id'].notna()]

filtered_df

filtered_df = merge_df[merge_df['group_id'].str.contains('T48A')]
filtered_df

# Agrupar por 'student_id' y contar los registros
student_counts = filtered_df.groupby('DT').size().reset_index(name='Asistencias')

# Mostrar los resultados
student_counts

from re import L
# Agrupar por 'student_id' y contar los registros

student_counts = filtered_df.groupby('DT').size().reset_index(name='Asistencias')

# Crear la columna 'Inasistencias'
student_counts['Inasistencias'] = 23 - student_counts['Asistencias']
# Mostrar los resultados
student_counts['DT'] = pd.to_datetime(student_counts['DT'])
student_counts['Dia'] = student_counts['DT'].dt.day_name()
student_counts

