# -*- coding: utf-8 -*-
"""Student.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-DCO8UbiLzGXFVYytGfAVn89QYc9w0Y
"""

import pandas as pd

groups_df = pd.read_csv('STUDENT_GROUP.csv')
groups_df.head()

attendance_df = pd.read_csv('attendance.csv')
attendance_df.head()

groups_df.dtypes

attendance_df.dtypes

groups_df['student_key'] = pd.to_numeric(groups_df['student_id'], errors='coerce').apply(lambda v: str(int(v)) if pd.notna(v) else None)

attendance_df['student_key'] = pd.to_numeric(attendance_df['STUDENT_ID'], errors='coerce').apply(lambda v: str(int(v)) if pd.notna(v) else None)

from zoneinfo import ZoneInfo

attendance_df['DTTM_utc'] = pd.to_datetime(attendance_df['DTTM'], errors='coerce', utc=True)

attendance_df['DTTM_local'] = attendance_df['DTTM_utc'].dt.tz_convert(ZoneInfo("America/Monterrey"))

attendance_df['DATE_local'] = attendance_df['DTTM_local'].dt.date

merged = groups_df[['group_id', 'student_key']].merge(
    attendance_df[['student_key','DATE_local']],
    on='student_key',
    how='inner'
)
merged.head()

roster = groups_df.groupby('group_id')['student_key'].nunique().rename('total_alum')

asistencia = (
    merged.groupby(['group_id','DATE_local'])['student_key']
    .nunique()
    .rename('asistieron')
    .reset_index()
)

asistencia = asistencia.merge(roster.reset_index(), on='group_id', how='left')
asistencia['ausencias'] = (asistencia['total_alum'] - asistencia['asistieron']).clip(lower=0)

max_por_grupo = asistencia.groupby('group_id')['ausencias'].transform('max')
asistencia['max_grupo'] = asistencia['ausencias'] == max_por_grupo

reporte_max = asistencia[asistencia['max_grupo']].sort_values(['group_id','DATE_local']).reset_index(drop=True)

print("Resumen:")
print(asistencia.head(20).to_string(index=False))

print("\nDías con más ausencias por grupo:")
print(reporte_max.to_string(index=False))
