# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9ptmZ4B3gRMN-hV-T81_Uv9r6CWRDk1
"""

import pandas as pd
import numpy as np

attendance = pd.read_csv('/content/attendance.csv')
studentgroupe = pd.read_csv('/content/STUDENT_GROUP.csv')

attendance.columns = ['id', 'student_id', 'date', 'date_time']
studentgroupe.columns = ['id', 'group_id', 'student_id']


studentgroupe['student_id'] = studentgroupe['student_id'].astype(str)
attendance['student_id'] = attendance['student_id'].astype(str)

attendance['date'] = pd.to_datetime(attendance['date'], errors='coerce')

attendance = attendance[attendance['date'].dt.year == pd.to_datetime('today').year]

filtro = studentgroupe.merge(attendance, on='student_id', how='inner')
filtro = filtro[filtro['group_id'] == '20251ST48A']

filtro['day'] = filtro['date'].dt.day

filtro2 = filtro.groupby('day').agg(
    asistencia_count=('student_id', 'count'),
    first_assistance_date=('date', 'first'),
    last_assistance_date=('date', 'last'),
    groupid=('group_id', 'first')
)

max_asistencias = filtro2['asistencia_count'].max()

filtro2['faltas'] = max_asistencias - filtro2['asistencia_count']

print(filtro2)

